#ifndef AUDIO_SHARED_H
#define AUDIO_SHARED_H

typedef enum {
	EXIT_REASON_UNKNOWN,
	EXIT_REASON_ERROR,
	EXIT_REASON_PLAY_OTHER,
	EXIT_REASON_STOP,
	EXIT_REASON_QUIT,
	EXIT_REASON_EOF
} exit_reason_t;

#endif
